### ISSUE TITLE
OSX error

### ISSUE THREAD

**Issue by dadoprom** [ducky64/labelmaker#2]
Me again. Testing on OSX following error poped up. On linux - ubuntu - it is working ok.
python labelmaker.py kp/kp-lepky-A4.svg kp/data.csv ss.svg
Traceback (most recent call last):
  File "labelmaker.py", line 89, in <module>
    for row in data_reader:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/csv.py", line 108, in next
    row = self.reader.next()
UnicodeEncodeError: 'ascii' codec can't encode character u'\u017e' in position 10: ordinal not in range(128)
MacBook-Air-uzivatela-David:labelmaker dadoprom$ python labelmaker.py kp/kp-lepky-A4.svg kp/data1.csv ss.svg
Traceback (most recent call last):
  File "labelmaker.py", line 89, in <module>
    for row in data_reader:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/csv.py", line 108, in next
    row = self.reader.next()
UnicodeEncodeError: 'ascii' codec can't encode character u'\u017e' in position 10: ordinal not in range(128)

**Comment by ducky64** [comment]
I can't support OS X because I don't have a Mac. So you're on your own here, but if you have a solution, feel free to submit a pull request.

I also see you're using Python 2.7. This was developed on Python 3, which significantly improves Unicode support. Unicode characters should work (but may be a bit finicky, depending on how you set the encoding in your CSV editor) and are part of the supernode labels test set (like the capital omega for ohms).

**Comment by dadoprom** [comment]
Ok, I will install Python 3 and will test, it is ok if it is not working on OSX, linux is ok.
